### ISSUE TITLE
Security vulnerability in hoek

### ISSUE THREAD

**Issue by jimmytheleaf** [WHRB/radio-api#2]
I get a weekly email for security vulnerabilities that tells me:

```
WHRB/radio-api
Known moderate severity security vulnerability detected in hoek < 5.0.3
defined in package-lock.json

package-lock.json update suggested: hoek ~> 5.0.3.
```

Dependency info with highlighted vuln can be found: https://github.com/WHRB/radio-api/network/dependencies

Is this API is in active use? If so, should update that; if not we could probably turn those warnings off.

**Comment by cpill0789** [comment]
It is in use. I'll update it now.

**Comment by cpill0789** [comment]
v1.3.1 which has been deployed removes the vulnerable dependency. Thanks for pointing this out!
